### PR TITLE
Pydantic

### PR DESCRIPTION
**Pull request by mom1**
Hi, your package impressed me. 

I propose to add the ability to validate and transform requests / responses using [pydantic](https://pydantic-docs.helpmanual.io/)

### CODE REVIEW

**Comment by MikeWooster** [comment]
Hi, thanks for putting this together.  Having a pydantic integration is really cool.

I'm not a huge fan of the suppression of imports going on, and I'm aware that following my inclusion of `jsonmarshal` I had forced people to use v.3.7+, which isn't ideal.  I was in the process of pulling this functionality out as a separate package (`api-client-jsonmarshal`).

How about you do the same for `api-client-pydantic`?  That way, there will be no weird dependency problems for current users of the original client and this package remains simpler (you only need to use it if you explicitly want to).  I'm happy to include a mention to the extension in this package too.  It should be relatively simple to pull the code you have already written into a new package.

**Comment by mom1** [comment]
Hey. Thanks for your api-client.
It is a great idea to send "jsonmarshal" and "pydantic" in separate packages.

I will make api-client-pydantic.
but could you please remove the "jsonmarshal" dependency in the api-client package?

**Comment by mom1** [comment]
And I will do a new PR. since some changes are needed in the api-client package for correct operation.

**Comment by mom1** [comment]
I created package [api-client-pydantic](https://github.com/mom1/api-client-pydantic)

and close this pr

**Pull request closed without merging**
